version: '3'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: es-container
    environment:
      - discovery.type=single-node
      - http.port=8080
    ports:
      - "8080:8080"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm start

volumes:
  es_data:
    driver: local
