version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: es-container
    environment:
      - discovery.type=single-node
      - http.port=8080
    ports:
      - "8080:8080"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-container
    depends_on:
      - elasticsearch
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm start

volumes:
  es_data:
    driver: local
