name: Build and Deploy Elasticsearch and Node.js Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker services
        run: docker-compose up --build -d

      - name: Clean up
        run: docker-compose down

      - name: Check Elasticsearch logs
        run: docker-compose logs elasticsearch

      - name: Check Node.js logs
        run: docker-compose logs node

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  

      - name: Authenticate Docker to Google Container Registry
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker-compose build --no-cache
          docker tag elasticsearch:7.17.3 gcr.io/${{ secrets.GCP_PROJECT_ID }}/elasticsearch:latest
          docker tag hsa1225continuousdeployment-node gcr.io/${{ secrets.GCP_PROJECT_ID }}/node:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/elasticsearch:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/node:latest

      - name: Deploy Elasticsearch to Google Cloud Run
        run: |
          gcloud run deploy elasticsearch-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/elasticsearch:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Node.js to Google Cloud Run
        run: |
          gcloud run deploy node-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/node:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated