name: Build and Deploy Elasticsearch and Node.js Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Login to Docker hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_LOGIN }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker to Google Container Registry
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker-compose build
          docker images
          docker tag continuous-deployment_node gcr.io/${{ secrets.GCP_PROJECT_ID }}/hsacicd:v1.0.0
          docker images
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/hsacicd:v1.0.0

      - name: Deploy Elasticsearch to Google Cloud Run
        run: |
          gcloud run deploy elasticsearch-service \
            --image elasticsearch:7.17.3 \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      - name: Deploy Node.js to Google Cloud Run
        run: |
          gcloud run deploy node-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/hsacicd:v1.0.0 \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
